services:
  userbot:
    build: .
    volumes:
      - ./:/app
      - ./sessions:/app/sessions
    environment:
      - UID=${UID:-1000}
      - GID=${GID:-1000}
    command: python main.py
    tty: true
    user: "0:0"